// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE_HeZZ3FJL20KNj61Hi-Y37jrUbT5wSY',
    appId: '1:526987789587:web:c44def96ace5d8dd9dc6e6',
    messagingSenderId: '526987789587',
    projectId: 'push-notification-9d6ec',
    authDomain: 'push-notification-9d6ec.firebaseapp.com',
    storageBucket: 'push-notification-9d6ec.appspot.com',
    measurementId: 'G-G7TJKD9459',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCifSWpSudgzM9SF4MLqLv8RUZMBuLHw8w',
    appId: '1:526987789587:android:e56db79bf64700a99dc6e6',
    messagingSenderId: '526987789587',
    projectId: 'push-notification-9d6ec',
    storageBucket: 'push-notification-9d6ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoPBznGmxQg72cx4uvg__eJDZ17lG4lI',
    appId: '1:526987789587:ios:165404ca32ac05829dc6e6',
    messagingSenderId: '526987789587',
    projectId: 'push-notification-9d6ec',
    storageBucket: 'push-notification-9d6ec.appspot.com',
    iosBundleId: 'com.example.pushNotificationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoPBznGmxQg72cx4uvg__eJDZ17lG4lI',
    appId: '1:526987789587:ios:fcf308d2a0beff9c9dc6e6',
    messagingSenderId: '526987789587',
    projectId: 'push-notification-9d6ec',
    storageBucket: 'push-notification-9d6ec.appspot.com',
    iosBundleId: 'com.example.pushNotificationDemo.RunnerTests',
  );
}
